### ISSUE TITLE
Partition of the continuous time scale

### ISSUE THREAD

**Issue by SarahFrem** [mahmoodlab/PORPOISE#2]
Hi, 

Thank you for sharing your work on survival analysis and the survival losses.
I've read this repo as well as MCAT along with your papers and I have one question: 

Is there any rationale for using the quartiles to partition the continuous time? or this can be task-dependent ? Have you try any other partitioning ?
Thank you

**Comment by fedshyvana** [comment]
We found it to work well as a heuristic - though feel free to try different number of bins and tune it as a hyperparameter for your task (we did not find a big difference in prognostic performance in another study that we did). Using percentiles instead of fixed cutoffs just ensures that there is equal number of data points to fall into each bin.
